### ISSUE TITLE
Check MPT state transition integrity when aggregating proof 

### ISSUE THREAD

**Issue by eigmax** [0xEigenLabs/eigen-zkvm#102]
Currently, we only check that the 2 proofs(of stark verifier circuits) are satisfiable independently, without checking the order relationship of the proofs.

Ref imps: https://github.com/0xPolygonHermez/zkevm-proverjs/blob/v0.7.0.0-rc.3/recursive/recursive2.circom.ejs#L177C3-L226C41

**Comment by cyl19970726** [comment]
start working
