### ISSUE TITLE
Unify field implementation

### ISSUE THREAD

**Issue by eigmax** [0xEigenLabs/eigen-zkvm#139]
- [] Now the bn128 and bls12381 are implemented via ff_ce in starky,  instead of using pairing_ce::{bn254, bls381} like we do in plonky.  Hence we should reuse the pairing_ce.

**Comment by eigmax** [comment]
Meanwhile, there are different literal strings to represent different curves, like BN128 and bn128, plz unify the curve name.

**Comment by ChengYueJia** [comment]
It's blocks by #130 .

**Comment by eigmax** [comment]
> Meanwhile, there are different literal strings to represent different curves, like BN128 and bn128, plz unify the curve name.

We first fix this issue by #142
