### ISSUE TITLE
Merge StarkSetup Serialization

### ISSUE THREAD

**Issue by eigmax** [0xEigenLabs/eigen-zkvm#214]
When serializing StarkSetup,  it generates 3 [files](https://github.com/0xEigenLabs/eigen-zkvm/blob/main/starky/src/stark_setup.rs#L24) in Program, StarkInfo, and ConstTree. As @leonardoalt 's suggestion, we can use io.Read/Write to represent the whole 3 files.

**Comment by leonardoalt** [comment]
That'd be great! In fact you only need to implement serde for the `StarkSetup` type, and we can do the `io::{Read, Write}` on our side.
