### ISSUE TITLE
Speedup witness calculation & Circuit from file

### ISSUE THREAD

**Issue by eigmax** [0xEigenLabs/eigen-zkvm#267]
![Image](https://github.com/0xEigenLabs/eigen-zkvm/assets/81497928/e122d51f-dfee-4d3c-9272-1e8d4147d6eb)

**Comment by eigmax** [comment]
The R1CS/WASM/PK are cached, but we actually load it from disc to memory.  If we keep caching it in memory, it can save us t1+t3+t4 = 63s,  which is more than 1/2 of the `groth16_prove`.

**Comment by Shivannsh** [comment]
Can i work on this issue ?

**Comment by eigmax** [comment]
> Can i work on this issue ?

Sure! Thanks, let us know if you have any question.  cc @ibmp33

**Comment by eigmax** [comment]
@Shivannsh  @ibmp33 has submit a pull request,  very thanks if you can take a review.
